services:
  backend:
    build: .
    container_name: cms-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}

      MAILERSEND_API_KEY: ${MAILERSEND_API_KEY}
      SENDER_NAME: ${SENDER_NAME}
      SENDER_EMAIL: ${SENDER_EMAIL}